#!/bin/bash

# background and border color
riverctl background-color 0x002222
riverctl border-color-focused 0xe46f22
riverctl border-color-unfocused 0x586e75

# keyboard layout
riverctl keyboard-layout br

# keyboard repet
riverctl set-repeat 50 300
