#!/bin/bash

# mod keys
mod="Super"
mod2="Alt"
volkey="Alt"

# screen locking?
LOCKFILE="/tmp/river-autostart.lock"

# terminal
terminal="alacritty msg create-window"

# app launcher
run="rofi -show run"

# resizing factor
factor=75

# tags [1..9]
all_tags=1
for i in {1..9}; do
	all_tags=$(($all_tags | (1 << $i)))
done
